In [1]:
from Project1_BayesianStructureLearning import *

In [2]:
bsl = BayesianStructureLearning('example/example.csv', 'test.gph')
bsl.solve()

[[3 3 2 3 1 3]
 [1 3 2 3 2 3]
 [3 1 1 2 3 1]
 [1 3 1 2 3 2]
 [2 3 3 2 2 1]
 [1 3 1 1 1 3]
 [1 3 3 1 2 3]
 [3 3 2 3 1 3]
 [1 3 1 3 2 1]
 [3 1 1 3 3 3]
 [2 3 3 3 2 3]
 [2 3 2 3 3 3]
 [2 2 3 1 1 3]
 [2 3 3 3 2 3]
 [1 1 2 3 3 2]
 [2 2 1 3 2 3]
 [1 2 1 3 2 3]
 [3 1 1 3 1 2]
 [3 1 1 3 3 3]
 [1 3 1 2 3 1]]
Import CSV Complete

Graph Search Complete

Scoring Complete

Write Graph Complete

Solve Complete



In [ ]:
import networkx as nx
import numpy as np

g = nx.DiGraph()
nodes = [0,1,2,3,]

In [8]:
import networkx as nx
import numpy as np

g = nx.DiGraph()
g.add_node(0)
g.add_node(1)
g.add_node(2)
g.add_node(3)
g.add_edge(0,3)
g.add_edge(1,3)
g.add_edge(2,3)
variables = list(g.nodes())

parents = [list(g.predecessors(var)) for var in variables]
numValues = [2,2,2,3]
q = [np.prod([numValues[parent] for parent in parents[var][:]]) for var in variables]
print(variables)
print(parents)
print(q)

[0, 1, 2, 3]
[[], [], [], [0, 1, 2]]
[1.0, 1.0, 1.0, 8]


In [9]:
import pandas as pd

pd.read_csv('example/example.csv').to_numpy()

array([[3, 3, 2, 3, 1, 3],
       [1, 3, 2, 3, 2, 3],
       [3, 1, 1, 2, 3, 1],
       [1, 3, 1, 2, 3, 2],
       [2, 3, 3, 2, 2, 1],
       [1, 3, 1, 1, 1, 3],
       [1, 3, 3, 1, 2, 3],
       [3, 3, 2, 3, 1, 3],
       [1, 3, 1, 3, 2, 1],
       [3, 1, 1, 3, 3, 3],
       [2, 3, 3, 3, 2, 3],
       [2, 3, 2, 3, 3, 3],
       [2, 2, 3, 1, 1, 3],
       [2, 3, 3, 3, 2, 3],
       [1, 1, 2, 3, 3, 2],
       [2, 2, 1, 3, 2, 3],
       [1, 2, 1, 3, 2, 3],
       [3, 1, 1, 3, 1, 2],
       [3, 1, 1, 3, 3, 3],
       [1, 3, 1, 2, 3, 1]])